In [2]:
import pandas as pd

In [ ]:
#LOAD DATASET

df=pd.read_csv(r"C:\Users\anjal\Downloads\archive (1)\Combined_dataset.csv")
print(df)

     product_id           title  \
0       8376765     Lino Perros
1       9136281  Tommy Hilfiger
2      17633752           Lavie
3       1376949          F Gear
4      13939916       MYTRIDENT
..          ...             ...
995    13698258           KREDO
996    16896006           GUESS
997     1708108        GIORDANO
998    19280114        Fastrack
999    18601682         BOLDFIT

                                   product_description  rating  ratings_count  \
0                       Women Navy Blue Solid Backpack     3.8             15
1                    Unisex Navy Blue Striped Backpack     4.5             67
2                       Aries Women Pink Mini Backpack     4.4            226
3           Unisex Navy & Grey Printed Burner Backpack     4.4           1052
4                             Men Blue Solid Bath Robe     4.7             12
..                                                 ...     ...            ...
995  Men FORTE Silver Automatic Skeleton Analogue W...     3.5             11
996  Women White Patterned Dial & White Straps Anal...     5.0             22
997  Women Rose Gold-Toned Mirrored Analogue Watch ...     2.8              5
998  Men Black Brass Dial & Black Stainless Steel S...     4.3             17
999                           Purple Textured Yoga Mat     3.8            161

     initial_price  discount   final_price currency  \
0             3995      58.0   "₹3,995.00"      INR
1             2899      35.0   "₹2,899.00"      INR
2             2999      65.0   "₹2,999.00"      INR
3             1675      52.0   "₹1,675.00"      INR
4             2899      17.0   "₹2,899.00"      INR
..             ...       ...           ...      ...
995          11890      50.0  "₹11,890.00"      INR
996           8900      45.0   "₹8,900.00"      INR
997           7950      50.0   "₹7,950.00"      INR
998           3295      20.0   "₹2,636.00"      INR
999            699      31.0     "₹699.00"      INR

                                                images  ...  \
0    http://assets.myntassets.com/assets/images/837...  ...
1    http://assets.myntassets.com/assets/images/913...  ...
2    http://assets.myntassets.com/assets/images/176...  ...
3    http://assets.myntassets.com/assets/images/137...  ...
4    http://assets.myntassets.com/assets/images/pro...  ...
..                                                 ...  ...
995  http://assets.myntassets.com/assets/images/136...  ...
996  http://assets.myntassets.com/assets/images/168...  ...
997  http://assets.myntassets.com/assets/images/170...  ...
998  http://assets.myntassets.com/assets/images/192...  ...
999  http://assets.myntassets.com/assets/images/186...  ...

                                       amount_of_stars what_customers_said  \
0    {"1_star":2,"2_stars":0,"3_stars":3,"4_stars":...                 NaN
1    {"1_star":3,"2_stars":4,"3_stars":2,"4_stars":...                 NaN
2    {"1_star":9,"2_stars":5,"3_stars":10,"4_stars"...                 NaN
3    {"1_star":33,"2_stars":21,"3_stars":69,"4_star...                 NaN
4    {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
..                                                 ...                 ...
995  {"1_star":3,"2_stars":0,"3_stars":2,"4_stars":...                 NaN
996  {"1_star":0,"2_stars":0,"3_stars":0,"4_stars":...                 NaN
997  {"1_star":2,"2_stars":1,"3_stars":0,"4_stars":...                 NaN
998  {"1_star":1,"2_stars":2,"3_stars":0,"4_stars":...                 NaN
999  {"1_star":24,"2_stars":8,"3_stars":22,"4_stars...                 NaN

        seller_name                                              sizes  \
0               NaN                               [{"size":"Onesize"}]
1               NaN                               [{"size":"Onesize"}]
2               NaN                                     [{"size":"S"}]
3               NaN                               [{"size":"Onesize"}]
4               NaN  [{"size":"M","value":"45.0in","value_name":"Fr...
..              ...                                                ...
995             NaN                               [{"size":"Onesize"}]
996             NaN                               [{"size":"Onesize"}]
997             NaN                               [{"size":"Onesize"}]
998  Tru███m R███il                               [{"size":"Onesize"}]
999             NaN                                [{"size":"Medium"}]

                                                videos  \
0                                ["rw-8376765_cae700"]
1                                ["rw-9136281_cae700"]
2    ["https://videos.myntassets.com/assets/videos/...
3    ["https://videos.myntassets.com/assets/videos/...
4                                                  NaN
..                                                 ...
995                                    ["pi-13698258"]
996  ["rw-16896006_cae700","https://videos.myntasse...
997                                                NaN
998                                                NaN
999                                                NaN

                                    seller_information  \
0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
995                                                NaN
996                                                NaN
997                                                NaN
998  Sho███o. ███-10█████████enu███████████████████...
999                                                NaN

                                      variations  \
0                                           [{}]
1                                        [{},{}]
2                            [{},{},{},{},{},{}]
3                                            NaN
4    [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
..                                           ...
995                                          NaN
996                                          NaN
997                    [{},{},{},{},{},{},{},{}]
998                                          NaN
999                                [{},{},{},{}]

                                            best_offer  \
0                                                   {}
1                                                   {}
2                                                   {}
3                                                   {}
4                                                   {}
..                                                 ...
995                                                 {}
996                                                 {}
997                                                 {}
998  {"applicable_on":"Orders above Rs. 1499 (only ...
999                                                 {}

                                           more_offers   category
0    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
1    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
2    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
3    [{"offer_name":"10% Instant Discount on Citi C...  backpacks
4    [{"offer_name":"10% Instant Discount on IndusI...  bath-robe
..                                                 ...        ...
995  [{"offer_name":"10% Instant Discount on Citi C...    watches
996  [{"offer_name":"10% Instant Discount on Citi C...    watches
997  [{"offer_name":"10% Instant Discount on Citi C...    watches
998  [{"offer_name":"10% Instant Discount on IndusI...    watches
999  [{"offer_name":"10% Instant Discount on Citi C...  yoga-mats

[1000 rows x 24 columns]

In [ ]:
#EXPLORING DATA
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [62]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [63]:
print(df.shape)

(1000, 24)

In [64]:
print("columns :\n ",df.columns.tolist())

columns :
  ['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [24]:
print("datatypes: \n",df.dtypes)

datatypes:
 product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said       float64
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [ ]:
#HANDLE MISSING VALUES

print(df.isnull().sum())

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [67]:
df['discount']=df["discount"].fillna(df["discount"].mean())
df['what_customers_said']    = df['what_customers_said'].fillna("No review")
df['seller_name'] = df['seller_name'].fillna(df['seller_name'].mode()[0])
df['videos']   = df['videos'].fillna("No video")
df['seller_information']    = df['seller_information'].fillna("No available")
df['variations'] = df['variations'].fillna(df['variations'].mode()[0])

print('Missing values per column (after):')
print(df.isnull().sum())

Missing values per column (after):
product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [ ]:
#FILTER ROWS AND SELECT COLUMNS
filtered_df = df[df["rating"] > 4][['product_id','title','rating','final_price']]
print("products with rating > 4\n")
print(filtered_df.head())

products with rating > 4

   product_id           title  rating  final_price
1     9136281  Tommy Hilfiger     4.5  "₹2,899.00"
2    17633752           Lavie     4.4  "₹2,999.00"
3     1376949          F Gear     4.4  "₹1,675.00"
4    13939916       MYTRIDENT     4.7  "₹2,899.00"
5    17198778             H&M     4.5  "₹1,399.00"

In [69]:
discount_products = df[df["discount"] > 50][['product_id','title','initial_price','discount','final_price']]
print("Products with discount greater than 50\n")
print(discount_products.head())

Products with discount greater than 50

   product_id        title  initial_price   discount  final_price
0     8376765  Lino Perros           3995  58.000000  "₹3,995.00"
2    17633752        Lavie           2999  65.000000  "₹2,999.00"
3     1376949       F Gear           1675  52.000000  "₹1,675.00"
5    17198778          H&M           1399  53.503982  "₹1,399.00"
6    19851824   AVI Living           1399  65.000000  "₹1,399.00"

In [ ]:
# CHECK FOR DUPLICATE VALUES
print(df.duplicated().sum())

0

no duplicates found

In [ ]:
#DERIVE NEW COLUMN : DISCOUNT AMOUNT
df["final_price"] = (
    df["final_price"]
    .astype(str)
    .str.replace('₹', '')
    .str.replace(',', '')
    .str.replace('"', '')
)

df["final_price"] = pd.to_numeric(df["final_price"])

df["discount_amount"] = (df["initial_price"] - df["final_price"])


print( df[ [ "title", "initial_price", "final_price", "discount_amount"]].head(50))

                      title  initial_price  final_price  discount_amount
0               Lino Perros           3995       3995.0              0.0
1            Tommy Hilfiger           2899       2899.0              0.0
2                     Lavie           2999       2999.0              0.0
3                    F Gear           1675       1675.0              0.0
4                 MYTRIDENT           2899       2899.0              0.0
5                       H&M           1399       1399.0              0.0
6                AVI Living           1399       1399.0              0.0
7                   My Room           2999       2999.0              0.0
8                   My Room           2999       2999.0              0.0
9                Story@home           2199       2199.0              0.0
10                MYTRIDENT           2199       2199.0              0.0
11                   Arrabi           3329        865.0           2464.0
12               BELLA CASA           1499        404.0           1095.0
13                    ROMEE           3499       3499.0              0.0
14                   DDecor           1599       1599.0              0.0
15             Home Ecstasy           1199       1199.0              0.0
16            DREAM WEAVERZ           2599       2599.0              0.0
17                   Arrabi           6329       6329.0              0.0
18                  Kastner           1399        223.0           1176.0
19           Tommy Hilfiger           2999       1799.0           1200.0
20          Ed-a-Mamma Baby            999        699.0            300.0
21                  Mactree           9060       1087.0           7973.0
22               London Rag           9599       3839.0           5760.0
23         The Souled Store            799        367.0            432.0
24                   Jockey            579        579.0              0.0
25  GROVERSONS Paris Beauty            399        299.0            100.0
26                    Susie            749        374.0            375.0
27                   Zivame            999        499.0            500.0
28                    Susie            699        398.0            301.0
29                   Tweens            720        604.0            116.0
30          Marks & Spencer           2999       2249.0            750.0
31                      max            449        449.0              0.0
32                    VStar            345        345.0              0.0
33                    VStar            345        345.0              0.0
34                  shyaway           2547       2547.0              0.0
35                      max            649        649.0              0.0
36                   Zivame            995        995.0              0.0
37                     ZINU            699        384.0            315.0
38                KARATCART           3397        815.0           2582.0
39            Jewels Galaxy           1329        305.0           1024.0
40                 MINUTIAE           1499       1499.0              0.0
41               Pepe Jeans            459        298.0            161.0
42               Van Heusen            649        649.0              0.0
43               DressBerry            299        215.0             84.0
44                     Soie            390        370.0             20.0
45                EROTISSCH            899        539.0            360.0
46               Chromozome           1199        395.0            804.0
47                  ABELINO           1899        379.0           1520.0
48                    Zoiro            499        499.0              0.0
49                   Zivame            799        399.0            400.0

In [76]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,discount_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,No review,Sup███om ███,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",No available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,No review,Sup███om ███,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",No available,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,No review,Sup███om ███,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",No available,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,No review,Sup███om ███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",No available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,0.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,No review,Sup███om ███,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",No video,No available,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,No review,Sup███om ███,"[{""size"":""Onesize""}]","[""pi-13698258""]",No available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,0.0
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,No review,Sup███om ███,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",No available,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,0.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,No review,Sup███om ███,"[{""size"":""Onesize""}]",No video,No available,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,0.0
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,No review,Tru███m R███il,"[{""size"":""Onesize""}]",No video,Sho███o. ███-10█████████enu███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,659.0
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,No review,Sup███om ███,"[{""size"":""Medium""}]",No video,No available,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,0.0

In [ ]:
#SAVING CLEAN DATA IN NEW CSV
df.to_csv(r"C:\Users\anjal\OneDrive\Desktop\cleaned_data.csv", index=False)

print("cleaned data is saved successfully")

cleaned data is saved successfully